IF OBJECT_ID(N'TeamSeason') IS NULL
BEGIN 
	CREATE TABLE NBA.TeamSeason
	(
		TeamSeasonID INT NOT NULL IDENTITY(1,1),
		TeamID INT NOT NULL FOREIGN KEY REFERENCES NBA.Team(TeamID),
		CoachName NVARCHAR(32)NOT NULL,
		[Year] INT NOT NULL UNIQUE,
		TeamSeed INT NOT NULL,

		
	);
END