IF OBJECT_ID(N'NBA.Player') IS NULL
BEGIN
	CREATE TABLE NBA.Player
	(
		PlayerID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Height NVARCHAR(8) NOT NULL,
		[Weight] INT NOT NULL,
		Birthdate NVARCHAR(32) NOT NULL,
		College NVARCHAR(32) NOT NULL,
		DraftPick INT NOT NULL
	);
END