IF OBJECT_ID(N'PlayerSeason')IS NULL
BEGIN
	CREATE TABLE NBA.PlayerSeason
	(
		PlayerSeasonID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		PlayerID INT NOT NULL FOREIGN KEY REFERENCES NBA.Player(PlayerID),
		TeamSeasonID INT NOT NULL FOREIGN KEY REFERENCES NBA.TeamSeason(TeamSeasonID),

		UNIQUE(PlayerID, TeamSeasonID)
	);
END