IF OBJECT_ID(N'NBA.Team') IS NULL
BEGIN
	CREATE TABLE NBA.Team
	(
		TeamID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		[Name] NVARCHAR(32) NOT NULL,
		ConferenceName NVARCHAR(32) NOT NULL,

		UNIQUE([Name])
	);
END